### ISSUE TITLE
Missing docker scripts

### ISSUE THREAD

**Issue by lastrafda** [mkheck/SpringBootUpAndRunning#1]
In chapter 6 you mention the existence of some docker scripts 

"As with the earlier Redis project and most other examples in this chapter, each data-aware service must be able to access a running database. Please refer to this book’s associated code repositories for Docker scripts to create and run suitable containerized database engines."

but I can't find them and as far as I know their source is not mentioned on the book

**Comment by fermat2a** [comment]
if you are still searching: https://github.com/mkheck/containerscripts-database is the place to check (according arrate side: https://www.oreilly.com/catalog/errata.csp?isbn=0636920338727). Of course the docker scripts do not fit to the example code, so you have to repair. But as also the example code is quite unusable this seems to be normal for the author...

**Comment by mkheck** [comment]
Not sure why I wasn't notified of your feedback @lastrafda, I didn't see it until @fermat2a's unkind - and frankly incorrect, as all code in the book has been run successfully by numerous people - comment...so thank you for that, Sascha! How can I help, José?

As I mentioned in the linked errata, there was a mixup with the O'Reilly materials and I don't seem to have access to update the repo. I've created this repo under my own Gh account to provide a better source for book-related materials.

Best to you both. Out of all things, good can come. Wishing you an amazing 2022.

**Comment by captainko** [comment]
Please share the Docker scripts

**Comment by captainko** [comment]
> @fermat2a's unkind - and frankly incorrect, as all code in the book has been run successfully by numerous people

I can confirm that I cannot run the code from chapter7

**Comment by mkheck** [comment]
> Please share the Docker scripts

Hi @captainko, the scripts I used can be found here: https://github.com/mkheck/containerscripts-database

Note that you will need to edit the scripts to reflect your machine/directory structure(s), but these are the scripts I used on my MacBook Pro.

Hope this helps!
Mark

**Comment by mkheck** [comment]
> > @fermat2a's unkind - and frankly incorrect, as all code in the book has been run successfully by numerous people
> 
> I can confirm that I cannot run the code from chapter7

Hi John, thanks for reaching out. If you haven't for this particular issue, could you git clone the repo and checkout the chapter7end branch (https://github.com/mkheck/springbootupandrunning/tree/chapter7end) and try running it as published? If that fails on your machine, please do share the error(s) you're seeing and we'll get you up and running.

Cheers,
Mark

**Comment by natnael-bedru** [comment]
Hello @mkheck i had to look here to the issues section just to find out about the docker issue. Could you update the readme of this git so that others might come across it easily

**Comment by mkheck** [comment]
Hi @natnael-bedru,

Thank you for reaching out. Excellent idea, I've updated the README with an Author's Addendum, including a link to the scripts repo.

Best to you with your code, and again, thanks for reaching out!

Mark
