### ISSUE TITLE
where are the code examples ? can't see any anymore!!

### ISSUE THREAD

**Issue by jreakerian** [mkheck/SpringBootUpAndRunning#2]
Code examples missing!!

**Comment by mkheck** [comment]
No, they're all right here...in this repository. To retrieve all branches, you must perform a _git clone_ or _git fetch_, then _git checkout <name_of_branch_you_wish_to_check_out>_ to open up the appropriate projects.

**Comment by hanct** [comment]
But how to view the repository code online, without doing clone or fetch or any checkout
